GET http://localhost:3000/auth/whoami
Accept: application/json

###
POST http://localhost:3000/auth/signout
Accept: application/json


###
GET http://localhost:3000/auth?email=dayus@email.com
Accept: application/json

###
GET http://localhost:3000/auth/2
Accept: application/json

###
GET http://localhost:3000/auth
Accept: application/json

### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "dayus2@email.com",
  "password": "password"
}

### Signin a new user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "dayus2@email.com",
  "password": "password"
}

### Update user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "password": "pass"
}

###
DELETE http://localhost:3000/auth/1
Accept: application/json
